indev/urls.py
from django.contrib import admin
from django.urls import path
from rest_framework.routers import DefaultRouter
from rest_framework.urlpatterns import format_suffix_patterns
from django.conf.urls.static import static
from django.views.generic import TemplateView

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

import settings.base as settings
from categories.views import CategoryListView
from questions.views import QuestionViewSet, QuestionDetailView, checkAnswerForQuestion

urlpatterns = [
    path('admin/', admin.site.urls),

    path('questions/', TemplateView.as_view(template_name='crud.html')),

    path('questions/<int:question_id>/', QuestionDetailView.as_view()),



    path('api/v1/categories/', CategoryListView.as_view()),
    path('api/v1/questions/<int:question_id>/<str:answer_text>/', checkAnswerForQuestion),
]

router = DefaultRouter()
router.register('api/v1/questions', QuestionViewSet, basename='question')
urlpatterns += router.urls

# hack to serve static files under docker without modifying nginx in docker
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += staticfiles_urlpatterns()
# urlpatterns = format_suffix_patterns(urlpatterns)

answers/models.py
from django.db import models

from questions.models import Question


class Answer(models.Model):
    text = models.TextField(max_length=1024)
    correct = models.BooleanField(default=False)

    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    def __str__(self):
        return self.text

categories/models.py
from django.db import models


class Category(models.Model):
    title = models.TextField(max_length=1024)

    def __str__(self):
        return self.title

questions/models.py
from django.db import models

from categories.models import Category

EASY_STR = 'Easy'
MEDIUM_STR = 'Medium'
DIFFICULT_STR = 'Difficult'

DIFFICULTY_CHOICES = (
    ('0', EASY_STR),
    ('1', MEDIUM_STR),
    ('2', DIFFICULT_STR)
)


class Question(models.Model):
    question = models.TextField(max_length=1024)

    difficulty = models.CharField(max_length=1,
                                  choices=DIFFICULTY_CHOICES,
                                  default=0
                                  )

    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.question

categories/views.py
from rest_framework import generics

from categories.models import Category
from categories.serializers import CategorySerializer


class CategoryListView(generics.ListAPIView):
    queryset = Category.objects.all().order_by('id')
    serializer_class = CategorySerializer

questions/views.py
from django.http import JsonResponse
from rest_framework import filters
from rest_framework import mixins
from rest_framework.generics import get_object_or_404

from rest_framework.viewsets import GenericViewSet
from django.views.generic import TemplateView

from random import shuffle

from indev.paginators import CustomPagination
from questions.filters import MyCustomFilter
from questions.models import Question
from questions.serializers import QuestionSerializer
from answers.models import Answer


class QuestionViewSet(
    mixins.RetrieveModelMixin,
    mixins.ListModelMixin,
    GenericViewSet
):
    queryset = Question.objects.all().order_by('id')
    serializer_class = QuestionSerializer
    pagination_class = CustomPagination

    filter_backends = [filters.SearchFilter, MyCustomFilter]
    search_fields = ['question']


def checkAnswerForQuestion(request, question_id, answer_text):
    """
    Check if given answer is correct
    """
    question = get_object_or_404(Question, id=question_id)
    correctAnswer = Answer.objects.filter(question=question).get(correct=True)
    if correctAnswer.text == answer_text:
        return JsonResponse({'correct': True}, status=200)
    else:
        return JsonResponse({'correct': False}, status=404)


# Template Views
class QuestionDetailView(TemplateView):
    template_name = "question.html"

    def get_context_data(self, **kwargs):
        context = super(QuestionDetailView, self).get_context_data(**kwargs)
        if kwargs['question_id']:
            question = Question.objects.get(id=kwargs['question_id'])
            context['question'] = question

            answers = list(Answer.objects.filter(question_id__exact=question.id))

            # Random order of answers
            shuffle(answers)
            context['answers'] = answers
        return context

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css">
    <link href="https://cdn.jsdelivr.net/npm/boxicons@2.0.5/css/boxicons.min.css" rel="stylesheet"/>
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet"/>
    <link href="https://cdn.datatables.net/1.12.1/css/dataTables.bootstrap5.min.css" rel="stylesheet"/>
    {% block stylesheet %}{% endblock stylesheet %}
</head>
<body>
<main>
    <div class="side-navbar active-nav d-flex justify-content-between flex-wrap flex-column" id="sidebar">
        <ul class="nav flex-column text-white w-100 p-2">
            {% block sidebar %}
            {% endblock %}
        </ul>
    </div>
    <!-- Main Wrapper -->
    <div class="p-4 my-container active-cont">
        <!-- Top Nav -->
        <nav class="navbar top-navbar navbar-light bg-light px-5">
            <a class="btn border-0" id="menu-btn"><i class="bx bx-menu"></i></a>
        </nav>
        <!--End Top Nav -->
        {% block content %}
        {% endblock content %}
    </div>

</main>
<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.1/jquery.min.js'></script>
<script src='https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js'></script>
<script src="{% static 'js/app.js' %}"></script>
{% block javascript %}
{% endblock javascript %}
</body>
</html>

templates/crud.html
{% extends 'base.html' %}
{% load static %}

{% block stylesheet %}

{% endblock stylesheet %}

{% block sidebar %}
    <a href="#" class=" h2 text-white m-2 text-decoration-none">
                Filters
            </a>
            <div class="category-wrapper flex-column" style="display:flex">
                <label for="categories">Categories</label>
                <select id="categories" class="w-100" name="categories[]" multiple="multiple"></select>
            </div>

            <div class="difficulty-wrapper flex-column" style="display:flex">
                <label for="difficulty">Difficulty</label>
                <select id="difficulty" class="w-100" name="difficulties[]" multiple="multiple">
                    <option value="0">easy</option>
                    <option value="1">medium</option>
                    <option value="2">difficult</option>
                </select>
            </div>

            <div class="search-wrapper flex-column" style="display:flex">
                <label for="search-text">Search Question</label>
                <input id="search-text" class="w-100" name="search"/>
            </div>

            <div class="search-wrapper flex-column" style="display:flex">
                <label for="limit" class="form-label">limit</label>
                <div style="display:flex;">
                    <input type="range" value="5" min="1" max="25" class="form-range" id="limit">
                    <input id="limit-val" style="width:100%; max-width: 23px; text-align: center" value="5" disabled/>
                </div>
            </div>
{% endblock %}

{% block content %}
        <h3 class="text-dark p-3">Questions</h3>

        <table id="questions-table" class="display table table-striped" style="width:100%">
            <thead>
            <tr>
                <th>#</th>
                <th>Question</th>
                <th>Difficulty</th>
                <th>Category</th>
            </tr>
            </thead>
            <tbody></tbody>
        </table>

{% endblock content %}

{% block javascript %}
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.12.1/js/dataTables.bootstrap5.min.js"></script>
    <script src="{% static 'js/crud.js' %}"></script>
{% endblock javascript %}

templates/question.html
{% extends 'base.html' %}
{% load static %}

{% block sidebar %}
    <a href="/questions" class=" h4 text-white m-2 text-decoration-none">Back to Questions</a>
    <h5 href="#" class="  text-white m-2 text-decoration-none">Question #{{ question.id }}</h5>
{% endblock %}

{% block content %}
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">{{ question }}</h5>
            <div style="display: flex;justify-content: space-between" class="w-100">
                <div style="">{{ question.category }}</div>
                <div style="">{{ question.get_difficulty_display }}</div>
            </div>
            <div class="answers-wrapper text-center p-2">
                {% for answer in answers %}
                    <button value="{{ answer.text }}" class="btn btn-primary answer-btn">{{ answer.text }}</button>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

{% block javascript %}
    <script> const question_id = "{{ question.id }}"</script>
    <script>
        $(document).ready(() => {
            $('.answer-btn').on('click', function () {
                const btns = $('.answer-btn').removeClass('btn-success').removeClass('btn-danger').addClass('btn-primary');
                const element = this;
                $.get('/api/v1/questions/' + question_id + '/' + $(this).val() + '/', function (data) {
                    if(data && data.correct) {
                        $(element).removeClass('btn-primary').toggleClass('btn-success');
                    }
                }).fail(function() {
                    $(element).removeClass('btn-primary').addClass('btn-danger');
                });
            });
        });
    </script>
{% endblock %}